# -*- coding: utf-8 -*-
"""Transfer Learning and Hyperparameter Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCvAxNjtAVbflrZZ44VKSU3F8ZslyKmi
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models,utils
from torch.utils.data import DataLoader
from matplotlib.pyplot import imshow
import numpy as np

BATCH_SIZE = 64
EPOCH = 5
LEARNING_RATE = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

DEVICE

"""#LOAD DATASET"""

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, num_workers=2)

NUM_CLASSES = 10

len(train_dataset), len(test_dataset)

"""#SIMPLE CNN"""

class SimpleCNN(nn.Module) :
  def __init__(self) :
    super(SimpleCNN, self).__init__()
    self.features = nn.Sequential(
        nn.Conv2d(3, 32, 3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),

        nn.Conv2d(32, 64, 3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
    )

    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(64 * 56 * 56, 256),
        nn.ReLU(),
        nn.Linear(256, NUM_CLASSES)
    )

  def forward(self, x) :
    x = self.features(x)
    x = self.classifier(x)
    return x

"""#FUNGSI TRAINING"""

def train_model(model, name) :
  model = model.to(DEVICE)
  criterion = nn.CrossEntropyLoss()
  optimizer = optim.Adam(
      filter(lambda p : p.requires_grad, model.parameters()),
      lr=LEARNING_RATE
  )

  print(f"\nTraining {name}")

  for epoch in range(EPOCH) :
    model.train()
    running_loss = 0

    for images, labels in train_loader :
      images, labels = images.to(DEVICE), labels.to(DEVICE)

      optimizer.zero_grad()
      outputs = model(images)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()

      running_loss += loss.item()

    print(f"Epoch {epoch+1}/{EPOCH}, Loss : {running_loss/len(train_loader):.3f}")

  return model

"""## FUNGSI TESTING"""

def test_model(model, name) :
  model.eval()
  correct = 0
  total = 0

  with torch.no_grad():
    for images, labels in test_loader:
      images, labels = images.to(DEVICE), labels.to(DEVICE)
      outputs = model(images)

      _, predicted = torch.max(outputs, 1)

      total += labels.size(0)
      correct += (predicted == labels).sum().item()

  acc = 100 * correct / total
  print(f"\n{name} Test Accuracy: {acc:.2f}%")
  return acc

"""#PROSES TRAINING"""

simple_model = SimpleCNN()
simple_model = train_model(simple_model, "Simple CNN")

"""#PROSES TESTING"""

test_model(simple_model, "Simple CNN")

"""#MEMBUAT RESNET-18"""

def get_resnet18():
  model = models.resnet18(weights='DEFAULT');

  for param in model.parameters():
    param.requires_grad = False

  #GANTI CLASSIFIER
  model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)

  return model

"""#TRAINING RESNET"""

resnet_model = get_resnet18()
resnet_model = train_model(resnet_model, "ResNet-18")

